[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
